Repository oidlabs-com/Lexoid, pull requests merged in 2024-12, with the labels that each got.

#29 pyqt5 OS dependency workaround
  Makefile
  poetry.lock
  pyproject.toml
Labels: chores

#27 Improve pdfplumber parsing to format markdown and detect hyperlinks
  lexoid/core/parse_type/static_parser.py
  lexoid/core/utils.py
  tests/test_parser.py
Labels: enhancement

#28 Add support for parsing docx files
  .gitignore
  examples/inputs/sample.docx
  lexoid/api.py
  lexoid/core/parse_type/static_parser.py
  lexoid/core/utils.py
  poetry.lock
  pyproject.toml
  tests/test_parser.py
Labels: enhancement, dev

#40 Improve PDFPlumber parsing
  lexoid/core/parse_type/static_parser.py
  tests/test_parser.py
Labels: dev

#39 Add initial support for Llama 3.2 11B through HF
  lexoid/core/parse_type/llm_parser.py
  poetry.lock
  pyproject.toml
  tests/benchmark.py
  tests/env_template
Labels: dev, eval
