Repository oidlabs-com/Lexoid, pull requests merged in 2025-04, with the labels that each got.

#84 Minor updates
  README.md
  docs/api.rst
  docs/benchmark.rst
  examples/inputs/sample.pptx
  examples/inputs/sample.xlsx
  lexoid/api.py
  lexoid/core/parse_type/llm_parser.py
  lexoid/core/parse_type/static_parser.py
  lexoid/core/utils.py
  poetry.lock
  pyproject.toml
  tests/api_cost_mapping.json
  tests/benchmark.py
  tests/test_parser.py
Labels: enhancement

#93 detecting horizontal lines and strikethrough words
  lexoid/core/parse_type/static_parser.py
  tests/test_parser.py
Labels: dev

#91 get email address and markdown in <>
  examples/inputs/bench_md.pdf
  lexoid/core/parse_type/static_parser.py
  tests/test_parser.py
Labels: dev

#89 Update check heading levels from static values to dynamic values
  lexoid/core/parse_type/static_parser.py
  tests/test_parser.py
Labels: dev

#90 Monospace font detection
  lexoid/core/parse_type/static_parser.py
  tests/test_parser.py
Labels: dev

#92 block quotes detection and markdown as | depending on the level
  lexoid/core/parse_type/static_parser.py
  tests/test_parser.py
Labels: dev

#94 Add support for Fireworks API
  README.md
  docs/api.rst
  docs/benchmark.csv
  docs/benchmark.rst
  docs/index.rst
  docs/update_benchmarks.py
  lexoid/core/parse_type/llm_parser.py
  lexoid/core/utils.py
  tests/api_cost_mapping.json
  tests/benchmark.py
Labels: enhancement, benchmark/eval, inference_related
