Repository oidlabs-com/Lexoid, pull requests merged in 2025-03, with the labels that each got.

#67 Update Google Colab link in usage to match updated link in badge
  README.md
Labels: documentation

#68 Code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#81 Add support for OpenRouter models
  README.md
  docs/benchmark.rst
  lexoid/core/parse_type/llm_parser.py
  tests/benchmark.py
Labels: enhancement, dev

#80 Return token cost when cost mapping is provided
  README.md
  docs/api.rst
  docs/benchmark.rst
  lexoid/api.py
  tests/api_cost_mapping.json
  tests/benchmark.py
  tests/test_parser.py
Labels: enhancement, dev, eval
