Repository oidlabs-com/Lexoid, pull requests merged in 2025-01, with the labels that each got.

#43 Add Colab example notebook and update README
  README.md
  examples/example_notebook_colab.ipynb
Labels: documentation

#42 Add initial support for Llama 3.2 models through Together AI
  README.md
  lexoid/core/parse_type/llm_parser.py
  lexoid/core/prompt_templates.py
  poetry.lock
  pyproject.toml
  tests/benchmark.py
  tests/env_template
Labels: enhancement

#48 Remove together python client dependency and use REST API calls instead
  lexoid/core/parse_type/llm_parser.py
  poetry.lock
  pyproject.toml
Labels: dev

#49 Add docs
  .github/workflows/deploy_docs.yml
  README.md
  docs/.nojekyll
  docs/Makefile
  docs/api.rst
  docs/benchmark.rst
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/installation.rst
  docs/make.bat
  docs/requirements.txt
  poetry.lock
  pyproject.toml
  tests/env_template
Labels: documentation
